Unheppcat/nor-seasonal-watch-list

- application/config/packages/framework.yaml
- application/migrations/Version20210309002415.php
- application/migrations/Version20210309004953.php
- application/src/Controller/DiscordController.php
- application/src/Controller/ElectionVoteController.php
- application/src/Controller/ShowSeasonScoreController.php
- application/src/Entity/ElectionVote.php
- application/src/Entity/Show.php
- application/src/Entity/ShowSeasonScore.php
- application/templates/base.html.twig
- application/templates/discord/index.html.twig
Hides the logout link when the user is not yet logged in.
> I 2 logout link visible too lon

- application/templates/base.html.twig
- application/templates/default/index.html.twig
Discord accounts that are not NoR members at all, or don't have the minimum required role, see a message telling them so.
All menu entries except logout are hidden from these users.
> Changes home page message for users with wrong rights

- application/config/packages/security.yaml
- application/src/Controller/DefaultController.php
- application/src/Controller/MyVoteController.php
- application/src/Security/AppDiscordAuthenticator.php
Also changes the default (home) page path from "/default" to "/".
> Forces logout to remain on scheme HTTPS

- application/config/packages/version.yaml
- application/public/js/MyVote.js
- application/src/Form/ShowSeasonScoreType.php
- application/templates/all_watch/index.html.twig
- application/templates/my_vote/index.html.twig
Your Watch selection changed to radio buttons.
Voting window date display much simplified.
Slightly better formatting in All Watches score table.
> Updates watch selector, vote date format, others

- application/public/css/navbar-top-fixed.css
- application/public/js/AllWatch.js
- application/src/Controller/AllWatchController.php
- application/src/Controller/MyVoteController.php
- application/src/Entity/Show.php
- application/templates/all_watch/index.html.twig
- application/templates/base.html.twig
- application/templates/default/index.html.twig
- application/templates/my_vote/index.html.twig
- application/templates/my_watch/index.html.twig
Various display improvements.
Main menu now indicates which entry is active.
Season picker form moved to the navbar.
The All Watches mobile view rearranged to be more compact, most information hidden at first.
Quick link to shows within the All Watches page implemented.
Quick link back to the top of the All Watches page implemented.
> Various display changes

- application/config/packages/version.yaml
- application/public/js/AllWatch.js
- application/src/Controller/AllWatchController.php
- application/templates/all_watch/index.html.twig
- application/templates/base.html.twig
Scrollspy-style update of the show picker.
Show picker pinned to the top.
> Makes better formatting for the quick navigation on all/watch narrow

- application/src/Controller/AllWatchController.php
- application/src/Controller/MyVoteController.php
- application/src/Controller/MyWatchController.php
- application/templates/all_watch/index.html.twig
- application/templates/base.html.twig
- application/templates/default/index.html.twig
- application/templates/my_vote/index.html.twig
- application/templates/my_watch/index.html.twig
From "Your watch", "All watches" and "Your vote".
> Changes labels to "Personal", "Community" and "Vote"

- application/config/packages/version.yaml
- application/public/js/MyVote.js
- application/src/Controller/MyVoteController.php
- application/src/Repository/ElectionRepository.php
- application/templates/my_vote/no_election.html.twig
Page displays info on the next upcoming election (if there is one) with a countdown timer.
> Changes inactive elections to remain on the vote page

- application/config/packages/version.yaml
- application/public/js/AllWatch.js
- application/templates/all_watch/index.html.twig
> Revised chart formatting

- application/config/packages/version.yaml
- application/public/css/navbar-top-fixed.css
They now match the colors used in the charts.
> Changes the detail table background colors

- application/src/Controller/AllWatchController.php
- application/src/Repository/ShowSeasonScoreRepository.php
- application/templates/all_watch/index.html.twig
Score lookup queries were failing to limit to one season.
Table row filtering was too complex and had logic errors. Most of the logic has been moved into the controller.
> Fixes problems in both score lookups and table row filtering

- application/templates/all_watch/index.html.twig
- application/templates/base.html.twig
- application/templates/my_watch/index.html.twig
Now placed to the right of the page title on the personal and community show lists. (Moves to above the title on vary narrow screens.)
Removed from the main navbar.
> Moves the season picker

- application/config/packages/version.yaml
- application/public/js/AllWatch.js
- application/public/js/MyWatch.js
- application/public/js/SelectSeason.js
- application/public/js/SelectShow.js
- application/templates/all_watch/index.html.twig
- application/templates/my_watch/index.html.twig
Moves duplicated JS code into single shared libraries: SelectSeason and SelectShow.
> Adds quick nav to the personal watch list

- application/migrations/Version20210320211535.php
- application/src/Controller/AllWatchController.php
- application/src/Entity/Show.php
- application/src/Service/AnilistApi.php
- application/templates/all_watch/index.html.twig
MAL show id retrieved from the Anilist API and stored locally.
Also changed the Anilist link URL to the value returned from Anilist, rather than constructing it locally from the Anilist show ID.
> Adds MAL links

- application/config/packages/version.yaml
- application/public/css/navbar-top-fixed.css
- application/public/js/AllWatch.js
- application/src/Controller/AllWatchController.php
- application/src/Repository/ShowRepository.php
- application/templates/all_watch/fragment/activity_summary_table.html.twig
- application/templates/all_watch/fragment/anilist_mal_link_buttons.html.twig
- application/templates/all_watch/fragment/individual_values_table.html.twig
- application/templates/all_watch/fragment/mood_icon.html.twig
- application/templates/all_watch/fragment/recommendations_summary_table.html.twig
- application/templates/all_watch/index.html.twig
- application/templates/my_watch/index.html.twig
Changes charts to stacked horizontal bar.
Revised formatting for all tables.
Removes the statistics table, incorporates the most important values into activity and recommendations.
Adds sort on activity and recommendations.
> Makes big changes to the community list

- application/config/packages/version.yaml
- application/migrations/Version20210324043131.php
- application/public/js/AllWatch.js
- application/src/Controller/AllWatchController.php
- application/src/Entity/Activity.php
- application/src/Entity/Score.php
- application/src/Form/ActivityType.php
- application/src/Form/ScoreType.php
- application/src/Repository/ShowRepository.php
- application/templates/all_watch/index.html.twig
Makes improvement to chart display.
Changes precision for score and activity values to 3 decimal places instead of 1.
Changes activity sorting and totals to use the Activity.value rather than being hard-coded into the controller and queries.
> Chart adjustments

- application/config/packages/version.yaml
- application/public/js/AllWatch.js
- application/src/Controller/AllWatchController.php
- application/templates/all_watch/index.html.twig
The max values for number of entries (in recommendations) and total value (in activity) were incorrectly calculated.
> Fixes chart bounds calculation problems

- application/templates/my_watch/fragment/jump_link_buttons.html.twig
- application/templates/my_watch/index.html.twig
The more closely match the buttons on the community list page.
> Rearranges personal jump buttons

- application/config/packages/version.yaml
- application/migrations/Version20210401030344.php
- application/public/js/AllWatch.js
- application/src/Controller/AllWatchController.php
- application/src/Entity/User.php
- application/src/Repository/ShowSeasonScoreRepository.php
- application/src/Security/AppDiscordAuthenticator.php
- application/src/Service/DiscordApi.php
- application/templates/all_watch/fragment/individual_values_table.html.twig
- application/templates/all_watch/index.html.twig
Displays user nickname when available
Sorts user score details by nickname when available
Stores Discord user nickname during login
Removes visible ghost underline in anchor links in the community list
Attempts to fix the quick jump to community in phones, by increasing the delay
> Use guild nickname

- application/migrations/Version20210404052052.php
- application/src/Controller/AccountController.php
- application/src/Entity/User.php
- application/src/Entity/UserPreferences.php
- application/templates/base.html.twig
The only preference currently is colorsMode (dark, light or 'os').
Stored as a JSON object for future flexibility.
> Saves user preferences in the database

- application/config/packages/security.yaml
- application/config/packages/twig.yaml
- application/config/packages/version.yaml
- application/config/services.yaml
- application/src/Controller/ApiController.php
- application/src/Controller/ApiSeasonsController.php
- application/src/Controller/ApiWatchesController.php
- application/src/Entity/Activity.php
- application/src/Entity/Score.php
- application/src/Entity/Season.php
- application/src/Entity/Show.php
- application/src/Entity/ShowSeasonScore.php
- application/src/Entity/User.php
- application/src/Repository/SeasonRepository.php
- application/templates/api/index.html.twig
Adds a minimal API to the application. Usable to retrieve data on seasons and the community responses for shows in a season.
> Mini api 2

- application/config/packages/version.yaml
- application/public/js/AllWatch.js
- application/src/Repository/ShowRepository.php
Also changes recommendation sort to by total, not average
> Displays recommendation chart full width

- application/config/packages/version.yaml
- application/public/js/AllWatch.js
- application/templates/all_watch/index.html.twig
Trying to fix the occasionally too-narrow charts
> Changes chart proportions

- application/config/packages/version.yaml
- application/public/js/AllWatch.js
- application/src/Controller/AllWatchController.php
- application/src/Service/SelectedAllWatchModeHelper.php
- application/templates/all_watch/fragment/mode_selector_form.html.twig
- application/templates/all_watch/index.html.twig
The switch form is on the wide version of the all-watch list itself, so available without navigating to the user preferences page and back.
> Implements control to switch all-watch view mode

- application/public/css/dark-main.css
- application/public/css/main.css
- application/public/js/AllWatch.js
- application/templates/all_watch/index.html.twig
Adds zero mark to the x-axis.
Changes neutral color to white.
Fixes one pixel gap in the condensed view sticky legend bar.
> Makes chart and other display revisions

- application/migrations/Version20210616025416.php
- application/public/css/dark-main.css
- application/src/Controller/AccountController.php
- application/src/Controller/AdminActivityController.php
- application/src/Controller/AdminElectionController.php
- application/src/Controller/AdminElectionVoteController.php
- application/src/Controller/AdminScoreController.php
- application/src/Controller/AdminSeasonController.php
- application/src/Controller/AdminShowController.php
- application/src/Controller/AdminShowSeasonScoreController.php
- application/src/Controller/AllWatchController.php
- application/src/Controller/ApiWatchesController.php
- application/src/Controller/DefaultController.php
- application/src/Controller/MyVoteController.php
- application/src/Controller/MyWatchController.php
- application/src/Entity/Election.php
- application/src/Form/ElectionType.php
- application/src/Repository/ElectionRepository.php
- application/templates/base.html.twig
- application/templates/default/index.html.twig
- application/templates/election/index.html.twig
- application/templates/election/show.html.twig
- application/templates/my_vote/index.html.twig
Also field for max votes allowed (not enforced yet).
Also displays vote active status in the main menu.
> Adds description and arbitrary title to elections

- application/config/packages/version.yaml
- application/public/css/dark-main.css
- application/public/css/main.css
- application/templates/all_watch/index.html.twig
- application/templates/base.html.twig
- application/templates/default/index.html.twig
- application/templates/my_vote/index.html.twig
Also a better solution for the secondary toolbar height.
Removes the main.css stylesheet from dark mode.
> Makes various vote page related tweaks

- deployment/rebuild-javscript-routes-heroku.sh
Well at least I think it's a typo
> Found a typo
